title: <p align="center"> Mojtaba Ghasemi </p>

logo: "/Images/MJ_Picture.jpg?raw=true"

description:
  <p align="center">
  <a href="PDF/MJ_CV_2024.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/mojtabaghasemi/">LinkedIn</a> |
  <a href="https://github.com/MJTGhasemi">GitHub</a>
  </p>

  <p align="justify">
  As a seasoned Data Scientist with a Ph.D. in Biomedical Engineering and a graduate degree in Data Science, I excel in developing advanced analytics and predictive models. My expertise lies in leveraging advanced analytics, machine learning, deep learning, LLMs, and natural language processing to drive business solutions, strongly emphasizing data querying, cleaning, transformation, and feature engineering. I have a proven track record of collaborating with engineering teams to drive business solutions and explaining complex analytical findings to non-technical audiences.
  <br><br>
  In addition to my technical expertise, I have a strong foundation in teaching and mentoring. I have developed and delivered curriculum for data science programs, educating students in both fundamentals and advanced topics, including machine learning and natural language processing.
  <br><br>
  I am actively seeking new challenges where I can leverage my skills to drive business growth and innovation through strategic data utilization, collaborating with cross-functional teams, developing innovative AI solutions, and enhancing data communication and visualization to support decision-making processes.
  <br><br>
</p>

theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
