title: <p align="center"> Mojtaba Ghasemi </p>

logo: "/Images/MJ_Picture.jpg?raw=true"

description:
  <p align="center">
  <a href="PDF/MJ_CV_2023.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/mojtabaghasemi/">LinkedIn</a> |
  <a href="https://github.com/MJTGhasemi">GitHub</a>
  </p>

  <p align="justify">
  Experienced Data Analyst with a Ph.D. in Biomedical Engineering and a strong foundation in mathematics and statistics. Leveraging my proficiency in data cleaning, processing, interpretation, and machine learning, I specialize in translating complex datasets into actionable business insights to aid decision-making. 
  <br><br>
  I am seeking new challenges in Data Science to drive business growth and innovation through strategic data utilization.
  <br><br>
  </p>

theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
