title: <p align="center"> Mojtaba Ghasemi </p>

logo: "/Images/MJ_Picture.jpg?raw=true"

description:
  <p align="center">
  <a href="PDF/MJ_CV_2023.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/mojtabaghasemi/">LinkedIn</a> |
  <a href="https://github.com/MJTGhasemi">GitHub</a>
  </p>

  <p align="justify">
  As a seasoned Data Scientist with a Ph.D. in Biomedical Engineering and a graduate degree in Data Science, I excel in developing advanced analytics and predictive models. My expertise lies in leveraging advanced analytics, machine learning, deep learning, LLMs, and natural language processing to drive business solutions, strongly emphasizing data querying, cleaning, transformation, and feature engineering. I have a proven track record of collaborating with engineering teams to drive business solutions and explaining complex analytical findings to non-technical audiences.
  <br><br>
  My career highlights include:
  <ul>
    <li>Improving data accessibility by 50% through revamping data visualization dashboards.</li>
    <li>Enhancing stakeholder engagement by 40% by translating complex technical data into clear dashboards.</li>
    <li>Boosting operational efficiency by 30% through cross-functional collaboration and AI application development.</li>
    <li>Improving AI and data science team proficiency by 45% by fostering a culture of continuous learning.</li>
    <li>Demonstrating leadership and problem-solving skills by leveraging advanced AI and NLP techniques, improving decision-making efficiency by 20%. Enhanced machine learning and NLP pipeline efficiency, showcasing adaptability and critical thinking, which increased model accuracy by 15% and reduced processing time by 30%.</li>
    <li>Exhibiting strong communication and teamwork skills by leading cross-functional teams to develop AI solutions, boosting operational efficiency by 30%. Initiated and guided the creation of an NLP product, demonstrating project management and technical leadership.</li>
    <li>Utilizing excellent communication and data visualization skills to translate complex technical data into clear dashboards and reports, enhancing stakeholder engagement by 40%. Revamped the company’s data visualization dashboard, improving data accessibility by 50%, reflecting strong decision-making and business acumen.</li>
    <li>Showcasing leadership and a commitment to education by mentoring teams in AI and data science best practices, fostering a culture of continuous learning, and improving team proficiency by 45%.</li>
  </ul>
  <br>
  In addition to my technical expertise, I have a strong foundation in teaching and mentoring. I have developed and delivered curriculum for data science programs, educating students in both fundamentals and advanced topics, including machine learning and natural language processing.
  <br><br>
  I am actively seeking new challenges where I can leverage my skills to drive business growth and innovation through strategic data utilization, collaborating with cross-functional teams, developing innovative AI solutions, and enhancing data communication and visualization to support decision-making processes.
  <br><br>
</p>

theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
